### ISSUE TITLE
Bug: address shellcheck warnings for shell scripts in winning entry directories

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/temp-test-ioccc#1973]
# Overview

There are a number of warnings, some of them are bugs, a few are just `shellcheck(1)` paranoia, found in shell scripts in winner directories that should be addressed sometime.  Nevertheless, nearly all `shellcheck(1)` warnings are worth addressing by chaining the code instead of disabling the warning.

We opened up this issue separately form issue #3 so as to not delay the resolution one that long running issue.  It most cases the `shellcheck(1)` warnings that are bugs are **not critical bugs**, and so may be addressed after issue #3 is closed.

Yes, this issue is a lower priority than finishing issue #3 .

We also opened up this issue now so that in the future, new or newly modified try scripts might avoid creating more of these `shellcheck(1)` warnings.

Also, rather than burden issue #3 with `shellcheck(1)` related questions, we opened up this separate issue where any questions or comments about `shellcheck(1)` warnings might be addressed as comments under this issue.

# shellcheck warnings found  in try shell scripts

```sh
find ???? -type f -name 'try*.sh' -print0 | xargs -0 -n 1 shellcheck
```

# shellcheck warnings found in non-try shell scripts

```sh
find ???? -type f ! -name 'try*.sh' -name '*.sh' -print0 | xargs -0 -n 1 shellcheck
```

# Useful "For more information" output

In most cases, the `shellcheck(1)` utility provides good advice on shell scripts.  When run on a single file, the output includes a "For more information" listing URLs that further explain the issue that the `shellcheck(1)` utility raised. 

NOTE: If you run the `shellcheck(1)` utility on more than one shell script at a time, the "For more information" listing only applies to the **LAST** file that  the `shellcheck(1)` utility processed.  Thus, we recommend that one run the `shellcheck(1)` utility on each shell script separately.

# Recommended way to disable shellcheck warnings

In certain cases the issue identified by `shellcheck(1)` may need be suppressed.   We urge disabling `shellcheck(1)` warnings **only for a very good reasons**.

When you **MUST** to disable a `shellcheck(1)`, we recommend one use the following convention.

Consider this `shellcheck(1)` warning:

```
In readme2index.sh line 702:
	if [[ $FILE_PATH == $FILE_GLOB ]]; then
                            ^--------^ SC2053 (warning): Quote the right-hand side of == in [[ ]] to prevent glob matching.

For more information:
  https://www.shellcheck.net/wiki/SC2053 -- Quote the right-hand side of == i...
```

There is a good reason why we want "glob matching" on the match, so we disable it by adding comment lines above the "_offending_" section:

```sh
        # SC2053 (warning): Quote the right-hand side of == in [[ ]] to prevent glob matching.
        # https://www.shellcheck.net/wiki/SC2053
        # shellcheck disable=SC2053
        if [[ $FILE_PATH == $FILE_GLOB ]]; then
```

The final added "shellcheck disable=SC2053" comment line is used by the  `shellcheck(1)` to disable the warning, and thus is needed.

The first added "SC2053 (warning): Quote ..." comment line is taken from the shell check message, without the "^--------^" part.

The comment lines added between the first and final lines are URLs that are printed by the `shellcheck(1)` utility at the end of the output, without the "-- ..." on the line.  These URL comments when the reader view the `shellcheck(1)` utility was converted about, and perhaps to better re-evaluate if the issue should be disabled.

If a line has multiple `shellcheck(1)` warnings, use something like this to document and disable the multiple warnings:

```sh
    # SC2046 (warning): Quote this to prevent word splitting.
    # https://www.shellcheck.net/wiki/SC2046
    # SC2086 (info): Double quote to prevent globbing and word splitting.
    # https://www.shellcheck.net/wiki/SC2086
    # shellcheck disable=SC2046,SC2086
```

It may be helpful to add a comment ABOVE the disable warning section as follows:

```
        #  We have to disable the warning to quote COMMAND because ...
        # and because ....
        # 
        # SC2053 (warning): Quote the right-hand side of == in [[ ]] to prevent glob matching.
        # https://www.shellcheck.net/wiki/SC2053
        # shellcheck disable=SC2053
        if [[ $FILE_PATH == $FILE_GLOB ]]; then
```

It will be helpful to separate the comment from the rest of the disabling comment by a single "#" line.

Even though the `shellcheck(1)` utility will carry forward the "disable=" line to the first non-comment, we still recommend that the comments used to disable warning immediately following the "offending" shell script line.

Finally, even though if make be easier to simply disable a `shellcheck(1)` warning and move on, one could do so with care as there are often very good reasons why the waring is being issued.

**Comment by xexyl** [comment]
Ironically **I was thinking of doing EXACTLY this**! Well some might be complicated like those in hibachi but otherwise. Please assign this to me.

I will look at doing this. For now I'll start at the years I'm not yet finished with and then after that go back looking at previous scripts.

**Comment by xexyl** [comment]
As for the try scripts I'll do that first probably. Many of them I did check but I then updated the scripts which might have changed that. Since I'm working on those anyway I'll do them now. Then I'll continue.

**Comment by xexyl** [comment]
.. more than I actually expected. Oops! Let me correct those and then I'll continue the next years.

**Comment by xexyl** [comment]
Thanks for assigning this to me. Most are actually incorrect warnings at least with the try scripts. In fact I think up the years I've reviewed (so all those I've improved upon) (< year 2005) all but one warning was incorrect and the warning that was correct was not actually a problem.

But since the others are in need of review anyway and others might need to be added it's better I don't address them yet. In fact modifying them now would be a burden because it would make it harder to keep track (albeit only slightly) of what ones need to be reviewed again.

The other scripts I will do AFTER that issue is resolved completely: well perhaps I'll do it with the years I've not looked at yet but maybe I won't: not sure.

I should warn you it was a very hard night last night and I do not feel well but I should be able to get some of 2005 done if not complete 2005. But for now I will be afk .. hoping to rest soon though I really don't think I will be able to. Nevertheless I will do more later however much that might be.

**Comment by lcn2** [comment]
Please use the suggested format above, so that the consistency may be used to examine and identify `shellcheck(1)` disabled warnings.

For example, the comment:

```
    # This warning from ShellCheck is incorrect:
    #
    #   SC2028 (info): echo may not expand escape sequences. Use printf.
    #
    # because we deliberately have \\n to show that there will be a newline printed
    # WITH printf(1). Thus this does show correct output.
    #
    # shellcheck disable=SC2028
    echo "$ printf \"The International Obfuscated C Code Contest\\nBest One-liner\\nby Laurion Burchall\" | ./ldb"
```

using the above suggested format would be:

```
    # This warning from ShellCheck is incorrect because we deliberately have \\n to show that there will be a newline
    # printed WITH printf(1). Thus this does show correct output.
    #
    # SC2028 (info): echo may not expand escape sequences. Use printf.
    # https://www.shellcheck.net/wiki/SC2028
    # shellcheck disable=SC2028
    echo "$ printf \"The International Obfuscated C Code Contest\\nBest One-liner\\nby Laurion Burchall\" | ./ldb"
```

In the future, an automated tool will attempt to use that above structure to re-examine disabled choices.

**Comment by xexyl** [comment]
> Please use the suggested format above, so that the consistency may be used to examine and identify `shellcheck(1)` disabled warnings.
> 
> 
> 
> For example, the comment:
> 
> 
> 
> ```
> 
>     # This warning from ShellCheck is incorrect:
> 
>     #
> 
>     #   SC2028 (info): echo may not expand escape sequences. Use printf.
> 
>     #
> 
>     # because we deliberately have \\n to show that there will be a newline printed
> 
>     # WITH printf(1). Thus this does show correct output.
> 
>     #
> 
>     # shellcheck disable=SC2028
> 
>     echo "$ printf \"The International Obfuscated C Code Contest\\nBest One-liner\\nby Laurion Burchall\" | ./ldb"
> 
> ```
> 
> 
> 
> using the above suggested format would be:
> 
> 
> 
> ```
> 
>     # This warning from ShellCheck is incorrect because we deliberately have \\n to show that there will be a newline
> 
>     # printed WITH printf(1). Thus this does show correct output.
> 
>     #
> 
>     # SC2028 (info): echo may not expand escape sequences. Use printf.
> 
>     # https://www.shellcheck.net/wiki/SC2028
> 
>     # shellcheck disable=SC2028
> 
>     echo "$ printf \"The International Obfuscated C Code Contest\\nBest One-liner\\nby Laurion Burchall\" | ./ldb"
> 
> ```
> 
> 
> 
> In the future, an automated tool will attempt to use that above structure to re-examine disabled choices.
> 
> 

Okay I will look at this tomorrow and if I have any questions I will let you know.

**Comment by lcn2** [comment]
> Okay I will look at this tomorrow and if I have any questions I will let you know.

Again, the point of the explicit form of the final "1+2x" comment lines (where x is the number of disabled warnings) is for a future automation tool that will assist in an reexamination of disabled `shellcheck(1)` warnings.

As suggested in [comment 1902806595](https://github.com/ioccc-src/temp-test-ioccc/issues/1973#issuecomment-1902806595), any rationale comments can be in free form, followed by an "empty" common lines, followed by "1+2x" comment lines in the above mentioned formed.

So if there were 3 different warnings that needed to be disabled:

```
    # This SC2028 warning from ShellCheck is incorrect because we deliberately have "\\n: to show that there will be
    # a newline printed WITH printf(1). Thus this does show correct output.
    #
    # And then there is SC2086 that shellcheck informs us about: normally this should be fixed, but in this special case
    # is not because of "reasons". 
    #
    # Finally in the case of SC2028, it would be far too difficult to try an eval the line because it would mess of
    # the previously mentioned "\\n" lines, and unwilling to turn it into "\\\\n" just to avoid this informative warning.
    #
    # SC2028 (warning): Quote this to prevent word splitting.
    # https://www.shellcheck.net/wiki/SC2046
    # SC2086 (info): Double quote to prevent globbing and word splitting.
    # https://www.shellcheck.net/wiki/SC2086
    # SC2028 (info): echo may not expand escape sequences. Use printf.
    # https://www.shellcheck.net/wiki/SC2028
    # shellcheck disable=SC2028,SC2046,SC2086
    echo $FOO "$ printf \"The International Obfuscated C Code Contest\\nBest One-liner\\nby Laurion Burchall\" | ./ldb"
```

Note that in the "free form text", you can use the "SCxxxx" symbol without having to use the text of the warning.
And of course, by "free form text" we mean you are free to form it, or not (😉) just as long as there is empty comment line followed by the 1+2x well formatted lines followed by the line that "offends" the `shellcheck(1)` utility.

**Comment by xexyl** [comment]
> > Okay I will look at this tomorrow and if I have any questions I will let you know.
> 
> Again, the point of the explicit form of the final "1+2x" comment lines (where x is the number of disabled warnings) is for a future automation tool that will assist in an reexamination of disabled `shellcheck(1)` warnings.
> 
By this do you mean the lines (using the example above):

```
# SC2028 (info): echo may not expand escape sequences. Use printf.
    # https://www.shellcheck.net/wiki/SC2028
    # shellcheck disable=SC2028
```

?

As for the other issue I had: I have to look at all 'shellcheck disable=...' because there were some I already disabled. That's not a problem of course but it does mean that there are more cases to look at.

> As suggested in [comment 1902806595](https://github.com/ioccc-src/temp-test-ioccc/issues/1973#issuecomment-1902806595), any rationale comments can be in free form, followed by an "empty" common lines, followed by "1+2x" comment lines in the above mentioned formed.
> 
Good it can be free form! Based on this I guess I am correct in my idea above - that those lines are indeed what I pasted. Is that so?

> So if there were 3 different warnings that needed to be disabled:
> 
> ```
>     # This SC2028 warning from ShellCheck is incorrect because we deliberately have "\\n: to show that there will be
>     # a newline printed WITH printf(1). Thus this does show correct output.
>     #
>     # And then there is SC2046 that shellcheck informs us about: normally this should be fixed, but in this special case
>     # is not because of "reasons". 
>     #
>     # Finally in the case of SC2086, it would be far too difficult to try an eval the line because it would mess of
>     # the previously mentioned "\\n" lines, and unwilling to turn it into "\\\\n" just to avoid this informative warning.
>     #
>     # SC2028 (warning): Quote this to prevent word splitting.
>     # https://www.shellcheck.net/wiki/SC2046
>     # SC2086 (info): Double quote to prevent globbing and word splitting.
>     # https://www.shellcheck.net/wiki/SC2086
>     # SC2028 (info): echo may not expand escape sequences. Use printf.
>     # https://www.shellcheck.net/wiki/SC2028
>     # shellcheck disable=SC2028,SC2046,SC2086
>     echo $FOO "$ printf \"The International Obfuscated C Code Contest\\nBest One-liner\\nby Laurion Burchall\" | ./ldb"
> ```
> 
Although not all those warnings are triggered by that line of course so I'm not sure how they connect. But maybe you just are giving an example of if one line has more than one warning?

> Note that in the "free form text", you can use just the "SCxxxx" symbol without having to refer to the full the text of the warning.
> 
Please elaborate here. Ah .. you mean just the ID and not the warning text itself, correct?


> And of course, by "free form text" we mean you are free to form it, or not (😉) just as long as there is empty comment line followed by the 1+2x well formatted lines followed by the line that "offends" the `shellcheck(1)` utility.
> 

Makes sense to me. Thanks

> Sorry, (tm Canada 🇨🇦) to place this requirement on these points.


Well that's quite okay! Appreciate the concern though.

**Comment by lcn2** [comment]
> > > Okay I will look at this tomorrow and if I have any questions I will let you know.
> > 
> > 
> > Again, the point of the explicit form of the final "1+2x" comment lines (where x is the number of disabled warnings) is for a future automation tool that will assist in an reexamination of disabled `shellcheck(1)` warnings.
> 
> By this do you mean the lines (using the example above):
> 
> ```
> # SC2028 (info): echo may not expand escape sequences. Use printf.
>     # https://www.shellcheck.net/wiki/SC2028
>     # shellcheck disable=SC2028
> ```
> 
> ?

Yes.  An example with x=1 warning silenced and 2*x+1 = 3 comments immediately above it.

**Comment by lcn2** [comment]
> Although not all those warnings are triggered by that line of course so I'm not sure how they connect. But maybe you just are giving an example of if one line has more than one warning?

It did indicate that this was just an example, not real code.

Here it a real 2-warning disabled example, with no commentary from `readme2index.sh` (NOTE: This code will soon be moved to another script):

```sh
    # We are evaluating the next line on purpose as $O_OPTSTR and ${OUTPUT_TOOL_OPTSTR[$VALUE]}
    # may contain multiple command options, we cannot simply double quote them (SC2086).
    # We need to let eval do its work split (SC2046) the values.
    #
    # SC2046 (warning): Quote this to prevent word splitting.
    # https://www.shellcheck.net/wiki/SC2046
    # SC2086 (info): Double quote to prevent globbing and word splitting.
    # https://www.shellcheck.net/wiki/SC2086
    # shellcheck disable=SC2046,SC2086
    OUTPUT_TOOL_OUTPUT=$(eval "$VALUE" $O_OPTSTR ${OUTPUT_TOOL_OPTSTR[$VALUE]} -- "${WINNER_PATH}")
```

Here is a single waning disable:

```sh
        # parse output tool options by evaluating by globbing and splitting (SC2086)
        # the $OUTPUT_TOOL_OUTPUT value.
        #
        # SC2086 (info): Double quote to prevent globbing and word splitting.
        # https://www.shellcheck.net/wiki/SC2086
        # shellcheck disable=SC2086
        eval parse_command_line $OUTPUT_TOOL_OUTPUT
```

**Comment by xexyl** [comment]
> > > > Okay I will look at this tomorrow and if I have any questions I will let you know.
> > > 
> > > 
> > > Again, the point of the explicit form of the final "1+2x" comment lines (where x is the number of disabled warnings) is for a future automation tool that will assist in an reexamination of disabled `shellcheck(1)` warnings.
> > 
> > 
> > By this do you mean the lines (using the example above):
> > ```
> > # SC2028 (info): echo may not expand escape sequences. Use printf.
> >     # https://www.shellcheck.net/wiki/SC2028
> >     # shellcheck disable=SC2028
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ?
> 
> Yes. An example with x=1 warning silenced and 2*x+1 = 3 comments immediately above it.

Thanks. Well I will look for lines in the form of `shellcheck disable=` later on. It makes sense now I think on it to worry about form later on all together rather than slowing down the progress of the scripts themselves. This after all is another issue (even if they're kind of connected).

I have to be away a while in about half an hour and after that I very likely won't get anything else done today. Still I finished 2006 and I got some fixes in the ioccc status tool and the man page for it done which is great! I can do more tomorrow, the next year most likely.

**Comment by lcn2** [comment]
Suggestion: Always put a "rationale" as to why the `shellcheck(1)` warning needs to be disabled in a comment above, followed by an empty comment line.  In that "rationale" if you wish to refer to a specific `shellcheck(1)` warning, use
just the "(SCxxxx)" symbol and not the wanting text as that test is in the 2*x+1 lines below the empty comment line. 

See above for example.  See the `bin/` tools for more examples.

**Comment by xexyl** [comment]
> Suggestion: Always put a "rationale" as to why the `shellcheck(1)` warning needs to be disabled in a comment above, followed by an empty comment line. In that "rationale" if you wish to refer to a specific `shellcheck(1)` warning, use just the "(SCxxxx)" symbol and not the wanting text as that test is in the 2*x+1 lines below the empty comment line.
> 
> See above for example. See the `bin/` tools for more examples.

I think I always do put a rationale there. The others are an idea too. When I address this issue I'll certainly check that all have a rationale.

**Comment by lcn2** [comment]
A quick and dirty scan:

```sh
shellcheck ????/*/*.sh | grep '^In ' | awk '{print $2;}' | sort -u
```

Shows that these shell scripts have some sort of `shellcheck(1)` notification:

- 1986/stein/stein.sh
- 1990/jaw/shark.sh
- 1990/stig/stig.sh
- 1993/dgibson/dgibson.sh
- 2013/dlowe/slflen.sh
- 2015/howe/prog-test.sh
- 2018/burton1/scripthd.sh
- 2018/burton2/freqcount.sh
- 2018/burton2/manpage.sh
- 2018/burton2/mkkeywords.sh
- 2018/burton2/runtest.sh
- 2018/burton2/spotcheck.sh
- 2018/burton2/tokcount.sh
- 2018/burton2/tokenfix.sh
- 2018/burton2/unob.sh
- 2019/ciura/pl.alt.sh
- 2019/ciura/pl.sh
- 2019/duble/check-os.sh
- 2019/poikola/try.alt.sh
- 2019/poikola/try.sh
- 2020/burton/check_be.sh
- 2020/burton/check_le.sh

This was posted as a simple FYI as this is **NOT** a priority issue.

**Comment by xexyl** [comment]
> A quick and dirty scan:
> 
> ```shell
> shellcheck ????/*/*.sh | grep '^In ' | awk '{print $2;}' | sort -u
> ```
> 
> Shows that these shell scripts have some sort of `shellcheck(1)` notification:
> 
> * 1986/stein/stein.sh
> * 1990/jaw/shark.sh
> * 1990/stig/stig.sh
> * 1993/dgibson/dgibson.sh
> * 2013/dlowe/slflen.sh
> * 2015/howe/prog-test.sh
> * 2018/burton1/scripthd.sh
> * 2018/burton2/freqcount.sh
> * 2018/burton2/manpage.sh
> * 2018/burton2/mkkeywords.sh
> * 2018/burton2/runtest.sh
> * 2018/burton2/spotcheck.sh
> * 2018/burton2/tokcount.sh
> * 2018/burton2/tokenfix.sh
> * 2018/burton2/unob.sh
> * 2019/ciura/pl.alt.sh
> * 2019/ciura/pl.sh
> * 2019/duble/check-os.sh
> * 2019/poikola/try.alt.sh
> * 2019/poikola/try.sh
> * 2020/burton/check_be.sh
> * 2020/burton/check_le.sh
> 
> This was posted as a simple FYI as this is **NOT** a priority issue.

Thanks. I'll be using the command you gave initially when I'm back at this. Still it's not so simple as the above list as some have warnings disabled but not the format you need it in (no URL for instance). I will be checking for these too.

The try scripts I'm not done with yet anyway so I'll address the shellcheck warnings when looking at them. Unfortunately I discovered some issues in them so I have to do another pass ... plus some consistency issues might want to be fixed though those are minor.

**Comment by lcn2** [comment]
We fixed the all the known shellcheck errors in:

* 1986/stein/stein.sh
* 1990/jaw/shark.sh
* 1990/stig/stig.sh
* 1992/gson/try.sh
* 1993/dgibson/dgibson.sh
* 2004/hibachi/src/hibachi-start.sh
* 2004/hibachi/src/localhost/test/shell/dump.sh
* 2004/hibachi/src/localhost/test/shell/test0.sh
* 2004/hibachi/src/localhost/test/shell/test1.sh
* 2004/hibachi/src/localhost/test/shell/test2.sh
* 2011/vik/try.sh
* 2013/dlowe/slflen.sh
* 2015/howe/prog-test.sh
* 2018/burton1/scripthd.sh
* 2018/burton2/freqcount.sh
* 2018/burton2/manpage.sh
* 2018/burton2/mkkeywords.sh
* 2018/burton2/runtest.sh
* 2018/burton2/spotcheck.sh
* 2018/burton2/tokcount.sh
* 2018/burton2/tokenfix.sh
* 2018/burton2/unob.sh
* 2019/ciura/pl.alt.sh
* 2019/ciura/pl.sh
* 2019/duble/check-os.sh
* 2019/poikola/try.alt.sh
* 2019/poikola/try.sh
* 2020/burton/check_be.sh
* 2020/burton/check_le.sh
* 2020/iocccsize-test.sh

It would be a good idea to test those scripts.

**Comment by lcn2** [comment]
We will address the shellcheck disable lines in the above set of files.

**Comment by xexyl** [comment]
> We will address the shellcheck disable lines in the above set of files.

That's helpful .. thanks! I'm hoping to start a task of issue 3 now. Just posted an update in the OT thread.

**Comment by lcn2** [comment]
Finished editing the shellcheck comments.

**Comment by xexyl** [comment]
> Finished editing the shellcheck comments.

Thanks! Well tomorrow hopefully my eyes will be kinder to me and I can look at the FAQ (which one part I'm unsure about - made a comment about it).
