### ISSUE TITLE
Enhacement: write tools that perform validation checks on all JSON files in the repo

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/temp-test-ioccc#2007]
Using similar technology developed by [chkentry in the mkiocccentry repo](https://github.com/ioccc-src/mkiocccentry/blob/master/chkentry.c), generate tools to validate JSON files used in this repo.

TODO:

* [x] Write a tool to validate a _YYYY/dir_ entry's `.entry.json` file including the semantics of the JSON file

* [x] Write a tool to validate an `author/author_handle.json` file including the semantics of the JSON file

## UPDATE 0

The above TODO has been updated as per changes introduced in commit aedb0172239504fb14249a23069e91367b10b58b/

**Comment by lcn2** [comment]
> Hmm .. priority compared to #3 please?

You will observe this issue does **NOT** have the Critical path TODO label.

> Now about this though. How will we bring in the jparse(3) to have it here?

The ` jparse(3)` library and tools will assumed to be installed.  If needed, a Makefile can test for this first.

**Comment by xexyl** [comment]
> > Hmm .. priority compared to #3 please?
> 
> You will observe this issue does **NOT** have the Critical path TODO label.
> 
True .. I did although at the time I asked I hadn't noticed the labels yet.

> > Now about this though. How will we bring in the jparse(3) to have it here?
> 
> The ` jparse(3)` library and tools will assumed to be installed. If needed, a Makefile can test for this first.

I'd guess that'll be necessary yeah. Well I have plenty others to work on first anyway and maybe you'll have started it by then. We'll see I guess.

**Comment by lcn2** [comment]
> > > Hmm .. priority compared to #3 please?
> > 
> > 
> > You will observe this issue does **NOT** have the Critical path TODO label.
> 
> True .. I did although at the time I asked I hadn't noticed the labels yet.
> 
> > > Now about this though. How will we bring in the jparse(3) to have it here?
> > 
> > 
> > The ` jparse(3)` library and tools will assumed to be installed. If needed, a Makefile can test for this first.
> 
> I'd guess that'll be necessary yeah. Well I have plenty others to work on first anyway and maybe you'll have started it by then. We'll see I guess.

We installed the [mkiocccentry repo](https://github.com/ioccc-src/mkiocccentry) for the first time, actually, because we need stuff such as the `location(1)` tool for issue #4 work.

**Comment by xexyl** [comment]
> > > > Hmm .. priority compared to #3 please?
> > > 
> > > 
> > > You will observe this issue does **NOT** have the Critical path TODO label.
> > 
> > 
> > True .. I did although at the time I asked I hadn't noticed the labels yet.
> > > > Now about this though. How will we bring in the jparse(3) to have it here?
> > > 
> > > 
> > > The ` jparse(3)` library and tools will assumed to be installed. If needed, a Makefile can test for this first.
> > 
> > 
> > I'd guess that'll be necessary yeah. Well I have plenty others to work on first anyway and maybe you'll have started it by then. We'll see I guess.
> 
> We installed the [mkiocccentry repo](https://github.com/ioccc-src/mkiocccentry) for the first time, actually, because we need stuff such as the `location(1)` tool for issue #4 work.

Wow! I'm amazed you hadn't installed it yet! I installed it ages ago and do it every so often (when there are changes). I have also used the `location(1)` tool for other issues as well! I'm not sure which ones and I suspect even those that are NOT related to the IOCCC! It's a very useful tool that I'm happy I could help with (like all the others of course).

**Comment by xexyl** [comment]
> Using similar technology developed by [chkentry in the mkiocccentry repo](https://github.com/ioccc-src/mkiocccentry/blob/master/chkentry.c), generate tools to validate JSON files used in this repo.
> 
> TODO:
> 
> * [ ]  Write a tool to validate a winner `.winner.json` file
> * [ ]  Write a tool to validate an `author/author_handle.json` file

Would you elaborate on these please? I mean one could simply use `jparse(1)` to do this. It could be a script file that takes a specific json file (allowing one to specify multiple files if desired, allowing one to specify path to `jparse(1)` etc., verbosity level and so on) and report whether it's valid or not. As both tools validate a json file the same script could be used (theoretically: at least with what little I know right now).

But perhaps you mean more than what a script could do and C code is needed? I woke up stupid early today and not sure what I'm going to get done :( but I do have a concern about reading the YYYY/README.md files for issue 3. I'll bring that up soon ..

**Comment by lcn2** [comment]
> > Using similar technology developed by [chkentry in the mkiocccentry repo](https://github.com/ioccc-src/mkiocccentry/blob/master/chkentry.c), generate tools to validate JSON files used in this repo.
> > TODO:
> > 
> > * [ ]   Write a tool to validate a winner `.winner.json` file
> > * [ ]   Write a tool to validate an `author/author_handle.json` file
> 
> Would you elaborate on these please? I mean one could simply use `jparse(1)` to do this. It could be a script file that takes a specific json file (allowing one to specify multiple files if desired, allowing one to specify path to `jparse(1)` etc., verbosity level and so on) and report whether it's valid or not. As both tools validate a json file the same script could be used (theoretically: at least with what little I know right now).

The `jparse(1)` tool and the underlying `jparse(3)` "_simply_" checks if something is JSON according to the _so called JSON spec_.   What is needed is a tool that check the semantics of the JSON is valid according to what the document is supposed to be.

Much like [checkentry(1)](https://github.com/ioccc-src/mkiocccentry/blob/master/soup/man/man1/chkentry.1) tool checks the semantics of JSON for `.info.json` and `.auth.json`, we need a tool that check the semantics of a `.winner.json` file, and checks the semantics of a _author/author_handle.json_ file.  So it not enough to simply for `jparse(3)` to state that such JSON files are valid JSON.  We need to check if the semantics of those files are valid as well.

### Here are just a few examples ...

One may assume that the semantic check for a given `.winner.json` file will be within the context of an IOCCC winner (e.g., some _YYYY/dir_ directory).   So, for example, the semantic check of such a `.winner.json` file would include testing if the manifest is complete.  Some "_programatic judgment_" is needed when determining if the "_ manifest is complete_".  

For example, files that are _constructed_, such as the `index.html` file and the "_YYYY_dir.tar.bz2_" might be listed in the manifest but do not (yet) exist. 

This implies that the tool that checks semantics of the `.winner.json` file might need to have a _-option_ to indicate if a file where _OK_to_edit_ is `false` is missing is a **fatal error**, or is just something to warn about, or if such a warning should be disabled altogether.

And if someone has compiled the entry and created files that are not in the manifest (.e.g, prog, prog.alt, prog.o, and/or some generated file), there may be files that exist but are not mentioned in the manifest.

This implies that the tool that checks semantics of the `.winner.json` file might need to have a _-option_ to indicate if a file in the _YYYY/dir_ directory is found that is **NOT** listed in the manifest is a **fatal error**, or is just something to warn about, or if such a warning should be disabled altogether.

The `.winner.json` file must contain a `author_handle` and that "author handle" must be in proper form.    Here proper form includes not only the `author_handle` contains proper characters (see `mkiocccentry(1)` and `chkentry(1)` for guidance) but if there exists an  _author/author_handle.json_ file exists and refers to the  _YYYY/dir_ directory as a `winner_id` in the `winning_entry_set`. 

Now this tool might need to be applied to a submission for which the IOCCC judges are considering as a winner, and thus the _author/author_handle.json_ might not yet exist (if the author is new), or that the _author/author_handle.json_  `winning_entry_set` does not (yet) refer to the `winner_id`. 

This implies that the tool that checks semantics of the `.winner.json` file might need to have a _-option_ to indicate if a missing _author/author_handle.json file is **fatal error**, or is just something to warn about, or if such a warning should be disabled altogether.  The same thing goes for a submission of someone who previous authored an IOCCC winner but for which the `winning_entry_set` does not (yet) refer to the `winner_id`. 

And the directory where the `.winner.json` is found might not yet be under a _YYYY_ year directory.  It might be elsewhere (such as what happens if the entry is being judged).  The same thing goes for the `author/` directory.

## Use cases

The _common_ / _default_ use case is to check an `.winner.json` file in a known  _YYYY/dir_ directory under the [winner repo](https://github.com/ioccc-src/winner) where everything is supposed to be in order, well formed, with no extra files, etc.  In this use case, some edit has been applied to the [winner repo](https://github.com/ioccc-src/winner) and the `.winner.json` file **MUST BE** semantically valid with no exceptions.

A valid alternate use case is check an `.winner.json` file of an IOCCC submission that will be announced as an IOCCC winner but for which the IOCCC judges have not yet created / updated things like a _author/author_handle.json_ file.  In this the `.winner.json` file needs to remind the IOCCC judges that the _author/author_handle.json_ file needs to be created  or updated.

A valid alternate use case is to check a repo such as the [temp-test-ioccc repo](https://github.com/ioccc-src/temp-test-ioccc) where some files might be missing, such as they are now.  And less common_ use case is to check a repo where the winner has been compiled and a `make clobber` is needed to be sure that "extra files not found in the manifest" is an error or are just OK.

A valid alternate use case is to check some directory in which a `.winner.json` file exists, but is **NOT part of the YYYY/dir heriarchy_**.  So there may need to be some _-option_ to indicate where the `author/` directory is to be found, and some  _-option_ to indicate the IOCCC _year_ of the directory, etc.

## AT THIS POINT

To above is **NOT** a complete list of details at this point.  This comment will **NOT** list all the details.  Your knowledge of now  `mkiocccentry(1)` and `chkentry(1)` work needs to come into play when writing such tools.

We have outlined use cases for the tool.  Those use cases can also serve a guide.

**Comment by lcn2** [comment]
Updated TODO text.

**Comment by xexyl** [comment]
> Updated TODO text.

Thanks .. and as for the more detailed comment I thought of it (though not nearly as many ideas) later on after I wrote the reply. This issue is much more complicated than I had hoped but it also is as complicated as probably expected so that's okay.

It might be that observing the chkentry tool will be helpful (in some ways: if nothing else starting with parsing the file or files) but the question of how to address how to import the semantics tables etc. (or adding new ones, whether in the other repo as a library or not) is quite another matter entirely: structure and other things besides.

Well this is not high priority so it doesn't matter right now but it's something to give some thought to I guess.

Afk a while now .. hope to do a bit more today than what I already did but I don't know: not feeling well at all I'm afraid. Hopefully that changes. Going to see if I can rest but I guess I won't be able to or won't be able to for long.

**Comment by lcn2** [comment]
We believe we have addressed all of the current questions that still need answering at this time. If we've missed something or something else needs to be clarified, please ask again.

**Comment by lcn2** [comment]
See [GH-issuecomment-2282221142](https://github.com/ioccc-src/mkiocccentry/issues/523#issuecomment-2282221142) for a discussion of tools that have a bering in this enhancement.

**Comment by lcn2** [comment]
We will point out that when issue #2614 is completed, all that will be needed as a simple wrapper script in the `bin/` directory and a make rule that drives that wrapper script in the `bin/` directory via `bin/all-run.sh`.

The wrapper script in the `bin/` directory would simply call the enhanced `chkentry(1)` with the appropriate args (such as the recommended `YYYY/dir` arg) when issue #2614 is completed.

**Comment by lcn2** [comment]
We believe we have addressed all of the current questions that still need answering at this time. If we've missed something or something else needs to be clarified, please ask again.

**Comment by lcn2** [comment]
While we do not have a semantics check per-se, a number of new bin tools have been added which performs all kinds of checks on JSON files.  As such, we can now close this issue.
