### ISSUE TITLE
[Bug] running `make gen_status` updates dates even if there were no updates, depending on last mod time

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/temp-test-ioccc#2529]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like this

### Describe the problem

The problem is simply this: if you look at the news.md file the last news update was 8 June 2024. But the last time the file was modified on the MacBook Pro is later. On the server it's a different date. This depends on the time the file was pulled or even if `touch(1)` was used. This means that I can't run the tool without updating the news (for instance) even if no update were made.

### Relevant images, screenshots or other files

For example on the laptop:

```diff
diff --git i/status.json w/status.json
index b10ea89282a56aed1459925125f6ae55b7af9b90..075e3805669ae3d1dc8b36488a66512b5b59f5ec 100644
--- i/status.json
+++ w/status.json
@@ -1,7 +1,7 @@
 {
     "no_comment" : "mandatory comment: because comments were removed from the original JSON spec",
     "IOCCC_status_version" : "1.0 2024-03-09",
     "contest_status" : "closed",
-    "news_update" : "2024-06-08T16:23:00+00:00",
+    "news_update" : "2024-06-25T18:12:58+00:00",
     "status_update" : "2024-04-30T22:51:32+00:00"
 }

```

but as noted above the last news update was 8 June, not 25 June. 

### What you expect

It should not update the dates unless there is actually an update. This might not be possible without an option that is necessary to explicitly update the date to some date (possibly the date of running) but perhaps there is another way to go about it too.

### Environment

```markdown
- OS: MacOS Sonoma 14.5
- Device: MacBook Pro M1
- Shell: GNU bash, version 5.2.26(1)-release (aarch64-apple-darwin23.2.0)

`bin/gen-status.sh` is up to date.
```

### Anything else?

Nothing else because I put the details in other locations.

**Comment by xexyl** [comment]
As an aside for issue template: I obviously need to add labels that should be added to different issue types ... can do that later, maybe today or maybe not, but this is kind of a reminder to myself. Afk a while ..

**Comment by xexyl** [comment]
> As an aside for issue template: I obviously need to add labels that should be added to different issue types ... can do that later, maybe today or maybe not, but this is kind of a reminder to myself. Afk a while ..

I could have sworn this is possible but it seems like it might not. That seems like a silly limitation. I could have sworn I saw it in documentation though. Afk again a while ..

**Comment by xexyl** [comment]
Hmm .. documentation does suggest it's possible. Will try it soon.

**Comment by lcn2** [comment]
The `make gen_status` is a rule under the section (as described in `make help`):

```
# Rules that are useful only for those IOCCC judges who maintain the official IOCCC website
```

We have, several times, performed `make gen_status` and then reverted the change it made to `status.json` and `status.html`.  Most recently when we updated the `inc` files that pertain to the top of the rules and guidelines HTML pages.  We reverted those changes to `status.json` and `status.html` because those induced changes were technicalities: not real news changes.

If someone else, other than an IOCCC judge, runs `make gen_status`, they will cause `status.json` and `status.html` because the modification time for their copy of news will change.  That's the way the rule functions.  Only the official repo clone that pushes to the official web site should be used to update the official last news modification time, just as only the official clone is the repo that would push a change of the IOCCC state (from say "closed" to "pending").

So we are not sure of this is one of those "INABIAF" cases.  We believe it is, but are willing to not close this issue right away to allow for further consideration of a different way that `make gen_status` should run.

**Comment by xexyl** [comment]
> The `make gen_status` is a rule under the section (as described in `make help`):
> 
> ```
> # Rules that are useful only for those IOCCC judges who maintain the official IOCCC website
> ```
> 

That's true .. though I did not really look at that rule. I have had to run it once at least - when there was an actual news update.

> We have, several times, performed `make gen_status` and then reverted the change it made to `status.json` and `status.html`. Most recently when we updated the `inc` files that pertain to the top of the rules and guidelines HTML pages. We reverted those changes to `status.json` and `status.html` because those induced changes were technicalities: not real news changes.

Actually I have done that too and really it's not a big deal to me either. It might be possible to do it some other way but thinking on it if one only worries about running it when there actually is an update (contest status change or news update) it doesn't really matter. I think it used to be that some other rules ran `make gen_status` which was a problem but since that was fixed it's not a big deal: at least I think.


> 
> If someone else, other than an IOCCC judge, runs `make gen_status`, they will cause `status.json` and `status.html` because the modification time for their copy of news will change. That's the way the rule functions. Only the official repo clone that pushes to the official web site should be used to update the official last news modification time, just as only the official clone is the repo that would push a change of the IOCCC state (from say "closed" to "pending").

Yes: as noted above just like you've had to undo that so too have I. And it's not really a big deal, all considered. It would be nice if it could work another way but is it really worth worrying about? Perhaps but perhaps not (see below).

> 
> So we are not sure of this is one of those "INABIAF" cases. We believe it is, but are willing to not close this issue right away to allow for further consideration of a different way that `make gen_status` should run.

It might indeed be a feature and not a bug. It might be in some ways (or sometimes) an inconvenient feature but that's quite all right. The only way I can think of at this time (besides just checking out/restoring the most recent update to the file) is like I thought of in the OP. But is that really worth it when it's not meant to be run except when news actually IS updated or the contest status is changed? It probably isn't.

Thus I will close this as something to not worry about. It really isn't a big deal and you yourself ran into the same problem and with the same thoughts. It was worth opening an issue just in case but I agree with you that it's just the way it works.

Thanks for the thoughts!
