### ISSUE TITLE
Should `robots.txt` be more restrictive?

### ISSUE THREAD

**Issue by SirWumpus** [ioccc-src/temp-test-ioccc#2615]
With all the hype and concern about AI bot scrapping of web sites, is it wise to allow every search engine crawlers and AI bots compete access to the whole of the IOCCC web site.  For the purposes of searching for sure I'd argue yes, but that might be hard to control.  For AI I question whether they should be allowed access to winner source tree at all.

AI would not "groke" the satirical nature of IOCCC as (originally examples of what NOT to do) or clever micro programs for education.  It could be argued that AI using IOCCC source, probably make worse code suggestions (which sounds good in many ways) to developers, which could be harmful without careful review (and many devs are lazy).

So should `robots.txt` be more restrictive?

* Deny all, including search engines that could serve dual masters.

* Deny all access to winners' source directories only.

* Deny only AI-bots?  Problem is maintaining a list of all active bots over time.

* Leave as is; they get what they deserve if they generate code based on winners.

**Comment by lcn2** [comment]
The IOCCC is open.
