### ISSUE TITLE
Enhancement: apply a more surgical approach to how fgets() replaces gets() and how exit() is used

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/temp-test-ioccc#936]
We have be asked to consider "a more surgical approach" to how fgets() replaces gets().

Consider the entry such as `1990/tbr/`.  The original `tbr.orig.c` is:

```c

#define D ,close(

char              *c,q              [512              ],m[              256
],*v[           99], **u,        *i[3];int         f[2],p;main       (){for
 (m[m        [60]=   m[62      ]=32   ]=m[*      m=124   [m]=       9]=6;
  e(-8)     ,gets      (1+(    c=q)     )||      exit      (0);     r(0,0)
   )for(    ;*++        c;);  }r(t,      o){    *i=i        [2]=    0;for
     (u=v  +98           ;m[*--c]         ^9;m [*c]          &32  ?i[*c
       &2]=                *u,u-             v^98              &&++u:

	3	)if(!m[*c]){for(*++c=0;!m[*--c];);
	*	--u= ++c;}u-v^98?strcmp(*u,"cd")?*c?pipe(f),o=f[
	1	]:
	4	,(p=fork())?e(p),o?r(o,0)D o)D*f):
	1	,wait(0):(o?dup2(*f,0)D*f)D o):*i?
	5	D 0),e(open(*i,0)):
	9	,t?dup2(t,1)D t):i[
	2	]?
	6	D 1),e(creat(i[2],438)):
	5	,e(execvp(*u,u))):e(chdir(u[1])*2):
	3	;}e(x){x<0?write(2,"?\n$ "-x/4,2),x+1||exit(1):
	5	;}
```

It has been suggested that by adding these 3 lines above the `#define D,..` line:

```c
int e(int x),r(int t,int o);
#define gets(x)fgets(x,512,stdin)
#define exit(x)(exit(x),1)
```

and using the following to compile:

```sh
cc -Wno-return-type -Wno-unused-value -Wno-implicit-int --include=string.h --include=fcntl.h \
--include=stdlib.h --include=sys/wait.h --include=unistd.h --include=stdio.h -o tbr tbr.c
```

The original look of the entry may be better preserved for modern compilers.

Please test this change to `1990/tbr/` and consider if it is possible to make similar changes to other entries where `gets()` was replaced with `fgets()`.

**Comment by lcn2** [comment]
We opened this new issue, @xexyl, as the general issue compiling entries has been closed.

**Comment by xexyl** [comment]
> We opened this new issue, @xexyl, as the general issue compiling entries has been closed.

Thanks!

Please assign this to me!

**Comment by xexyl** [comment]
Thanks for assigning this to me. 

And I agree with it btw. Some of them I have done but not all are necessarily possible. 

The choo choo entry (which doesn't use any of the respective functions) I jad to add some whitespace to keep the formatting as close to possible but let it still work: which it no longer did. 

Fortunately for this issue it is very easy to find entries modified. I guess that I can worry about that when I am focusing on this repo at the time you suggested. 

I would be kind of surprised if every entry can be changed this way but some probably can be. 

I still likely have in my head how these changes were made so that will help in working this issue out. 

With git it's also easy to see how I made any changes even when there's more than one commit. 

I don't think that many entries have this change. It might be that this can be done in a few sittings but we shall see. 

I hope to reply to the json level stuff today and maybe I can look at some of this today. I can see it both ways. 

I unfortunately do have other things I must do and like I said I have been awake too many hours but hopefully it will work out, today. 

I got a really annoying email from the main computer today: one of the HDDs has read errors. I was able to order a new one that is supposed to arrive today though maybe I should have bought an additional one so I can set up a hig@ level of raid. Well anyway fortunately I had credit at Amazon though I was hoping to use that for something else. 

Tomorrow will be annoying but hopefully none of the other disks start to die anytime soon. They are all quite old so I guess it's not that surprising. Strange that the error is not in smartd though ...

Anyway that's just an aside. I will certainly look at this issue hopefully sometime soon.

**Comment by xexyl** [comment]
It's funny but now I have a chance to look at this a bit better: I had the thought of changing the definition of `gets()` but I did not know if it was technically allowed. I thought it was undefined.

I think that this probably will work in many cases. I think it might not in all but it might in some. It might even be that the define of `gets` can be added to the Makefile to make it even cleaner.

**Comment by xexyl** [comment]
> It's funny but now I have a chance to look at this a bit better: I had the thought of changing the definition of `gets()` but I did not know if it was technically allowed. I thought it was undefined.
> 
> I think that this probably will work in many cases. I think it might not in all but it might in some. It might even be that the define of `gets` can be added to the Makefile to make it even cleaner.

But I'll do this when it's time to work on this repo. I'd rather it be done this way. Again I thought it was undefined to redefine symbols that are reserved. I actually like this idea much more and it's one I have had before. It will take a bit of work with looking at what it once looked like but it should be fine. I fortunately have documentation of which entries need to be checked here. Anyway I'll do this either when it's time again to work on this repo or else I feel up to this and not the others. Though of course there are other issues open with this repo too.

**Comment by lcn2** [comment]
> It's funny but now I have a chance to look at this a bit better: I had the thought of changing the definition of `gets()` but I did not know if it was technically allowed. I thought it was undefined.

That is a fair point.
 
> I think that this probably will work in many cases. I think it might not in all but it might in some. It might even be that the define of `gets` can be added to the Makefile to make it even cleaner.

The idea of moving the two defines into the Makefile is interesting.

We suspect the order of the `-Dstuff`, being after the `--include` lines, might be important.

It is interesting that one doesn't need to `-Ustuff` after the `--include` lines but before the `-Dstuff` (or does one need to?) as `exit(3)` and `gets(3)` might be macros as defined in the include files.

We recall that in a few cases, the use of `exit(3)` had to be played with, so we will update the title of this as well.

**Comment by xexyl** [comment]
> > It's funny but now I have a chance to look at this a bit better: I had the thought of changing the definition of `gets()` but I did not know if it was technically allowed. I thought it was undefined.
> 
> That is a fair point.

So what should be done?

> 
> > I think that this probably will work in many cases. I think it might not in all but it might in some. It might even be that the define of `gets` can be added to the Makefile to make it even cleaner.
> 
> The idea of moving the two defines into the Makefile is interesting.
> 
> We suspect the order of the `-Dstuff`, being after the `--include` lines, might be important.
> 
Very likely. Or in some cases they have to come before but of course if redefining symbols then it'd have to come after yes.

> It is interesting that one doesn't seem to need to `-Ustuff` after the `--include` lines but before the `-Dstuff` as `exit(3)` and `gets(3)` might be macros as defined in the include files.
> 

Yes that is interesting indeed.

> We recall that in a few cases, the use of `exit(3)` had to be played with, so we will update the title of this as well.

I did do that yes. There might be other things that could be done to make other fixes more 'original' though some will be too complicated to do that with. I can think of many examples off the top of my head.

Anyway what do you want me to do with redefining things?

**Comment by xexyl** [comment]
BTW as far as ...

```c
#define gets(x)fgets(x,512,stdin)
```

goes it's not that simple because of the issue that `fgets()` stores the newline and `gets()` does not. In one case it could not be fixed but it was worth the fix. In another case it prevents the code from working right. In other cases it was not a problem to fix.

**Comment by lcn2** [comment]
> > > It's funny but now I have a chance to look at this a bit better: I had the thought of changing the definition of `gets()` but I did not know if it was technically allowed. I thought it was undefined.
> 
> > 
> 
> > That is a fair point.
> 
> 
> 
> So what should be done?
> 
> 
> 
> > 
> 
> > > I think that this probably will work in many cases. I think it might not in all but it might in some. It might even be that the define of `gets` can be added to the Makefile to make it even cleaner.
> 
> > 
> 
> > The idea of moving the two defines into the Makefile is interesting.
> 
> > 
> 
> > We suspect the order of the `-Dstuff`, being after the `--include` lines, might be important.
> 
> > 
> 
> Very likely. Or in some cases they have to come before but of course if redefining symbols then it'd have to come after yes.
> 
> 
> 
> > It is interesting that one doesn't seem to need to `-Ustuff` after the `--include` lines but before the `-Dstuff` as `exit(3)` and `gets(3)` might be macros as defined in the include files.
> 
> > 
> 
> 
> 
> Yes that is interesting indeed.
> 
> 
> 
> > We recall that in a few cases, the use of `exit(3)` had to be played with, so we will update the title of this as well.
> 
> 
> 
> I did do that yes. There might be other things that could be done to make other fixes more 'original' though some will be too complicated to do that with. I can think of many examples off the top of my head.
> 
> 
> 
> Anyway what do you want me to do with redefining things? 

Experiment and try things: those were just ideas to explore.

**Comment by xexyl** [comment]
> > > > It's funny but now I have a chance to look at this a bit better: I had the thought of changing the definition of `gets()` but I did not know if it was technically allowed. I thought it was undefined.
> > 
> > 
> > > 
> > 
> > 
> > > That is a fair point.
> > 
> > 
> > So what should be done?
> > > 
> > 
> > 
> > > > I think that this probably will work in many cases. I think it might not in all but it might in some. It might even be that the define of `gets` can be added to the Makefile to make it even cleaner.
> > 
> > 
> > > 
> > 
> > 
> > > The idea of moving the two defines into the Makefile is interesting.
> > 
> > 
> > > 
> > 
> > 
> > > We suspect the order of the `-Dstuff`, being after the `--include` lines, might be important.
> > 
> > 
> > > 
> > 
> > 
> > Very likely. Or in some cases they have to come before but of course if redefining symbols then it'd have to come after yes.
> > > It is interesting that one doesn't seem to need to `-Ustuff` after the `--include` lines but before the `-Dstuff` as `exit(3)` and `gets(3)` might be macros as defined in the include files.
> > 
> > 
> > > 
> > 
> > 
> > Yes that is interesting indeed.
> > > We recall that in a few cases, the use of `exit(3)` had to be played with, so we will update the title of this as well.
> > 
> > 
> > I did do that yes. There might be other things that could be done to make other fixes more 'original' though some will be too complicated to do that with. I can think of many examples off the top of my head.
> > Anyway what do you want me to do with redefining things?
> 
> Experiment and try things: those were just ideas to explore.

Sure .. I had the thought too as noted but isn't it UB to redefine reserved words? If it is what would you like me to do? I think something like `Gets` or other case is ugly but maybe not? I guess it could become `steg` - short for stegosaurus and with the same letters but that doesn't feel any more authentic either and it might be worse too. I suppose `_gets()` or `gets_()` but that looks bad to me too.

What do you think ?

**Comment by lcn2** [comment]
> > > > > It's funny but now I have a chance to look at this a bit better: I had the thought of changing the definition of `gets()` but I did not know if it was technically allowed. I thought it was undefined.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > That is a fair point.
> 
> > > 
> 
> > > 
> 
> > > So what should be done?
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > > I think that this probably will work in many cases. I think it might not in all but it might in some. It might even be that the define of `gets` can be added to the Makefile to make it even cleaner.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > The idea of moving the two defines into the Makefile is interesting.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > We suspect the order of the `-Dstuff`, being after the `--include` lines, might be important.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > Very likely. Or in some cases they have to come before but of course if redefining symbols then it'd have to come after yes.
> 
> > > > It is interesting that one doesn't seem to need to `-Ustuff` after the `--include` lines but before the `-Dstuff` as `exit(3)` and `gets(3)` might be macros as defined in the include files.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > Yes that is interesting indeed.
> 
> > > > We recall that in a few cases, the use of `exit(3)` had to be played with, so we will update the title of this as well.
> 
> > > 
> 
> > > 
> 
> > > I did do that yes. There might be other things that could be done to make other fixes more 'original' though some will be too complicated to do that with. I can think of many examples off the top of my head.
> 
> > > Anyway what do you want me to do with redefining things?
> 
> > 
> 
> > Experiment and try things: those were just ideas to explore.
> 
> 
> 
> Sure .. I had the thought too as noted but isn't it UB to redefine reserved words? If it is what would you like me to do? I think something like `Gets` or other case is ugly but maybe not? I guess it could become `steg` - short for stegosaurus and with the same letters but that doesn't feel any more authentic either and it might be worse too. I suppose `_gets()` or `gets_()` but that looks bad to me too.
> 
> 
> 
> What do you think ?

Try the method of just defining the macros on the command line after the command line includes and see if it works well.

**Comment by xexyl** [comment]
> > > > > > It's funny but now I have a chance to look at this a bit better: I had the thought of changing the definition of `gets()` but I did not know if it was technically allowed. I thought it was undefined.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > That is a fair point.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > So what should be done?
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > I think that this probably will work in many cases. I think it might not in all but it might in some. It might even be that the define of `gets` can be added to the Makefile to make it even cleaner.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > The idea of moving the two defines into the Makefile is interesting.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > We suspect the order of the `-Dstuff`, being after the `--include` lines, might be important.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Very likely. Or in some cases they have to come before but of course if redefining symbols then it'd have to come after yes.
> > 
> > 
> > > > > It is interesting that one doesn't seem to need to `-Ustuff` after the `--include` lines but before the `-Dstuff` as `exit(3)` and `gets(3)` might be macros as defined in the include files.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Yes that is interesting indeed.
> > 
> > 
> > > > > We recall that in a few cases, the use of `exit(3)` had to be played with, so we will update the title of this as well.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I did do that yes. There might be other things that could be done to make other fixes more 'original' though some will be too complicated to do that with. I can think of many examples off the top of my head.
> > 
> > 
> > > > Anyway what do you want me to do with redefining things?
> > 
> > 
> > > 
> > 
> > 
> > > Experiment and try things: those were just ideas to explore.
> > 
> > 
> > Sure .. I had the thought too as noted but isn't it UB to redefine reserved words? If it is what would you like me to do? I think something like `Gets` or other case is ugly but maybe not? I guess it could become `steg` - short for stegosaurus and with the same letters but that doesn't feel any more authentic either and it might be worse too. I suppose `_gets()` or `gets_()` but that looks bad to me too.
> > What do you think ?
> 
> Try the method of just defining the macros on the command line after the command line includes and see if it works well.

That's what I'll do first when I get to it then.

**Comment by xexyl** [comment]
I know why it won't work with the `-D` and it's quite unfortunate what it is too. :(

Consider this. If in the command line we define `gets()` to `fgets()` what happens? It means that there are two definitions of `fgets()` and they are conflicting. So you get something like...

```makefile
# Defines that are needed to compile
#
CDEFINE= -Ugets -Ufgets -D'gets(x)'='fgets(x,232,stdin)'

# Include files that are needed to compile
#
CINCLUDE= -include stdio.h -include stdlib.h -include time.h

# Optimization
#
OPT= -O3

# Default flags for ANSI C compilation
#
CFLAGS= ${CSTD} ${CWARN} ${ARCH} ${CINCLUDE} ${CDEFINE} ${OPT}
```

Observe how I reordered the include / defines first. Note also that I tried to use `-U` first though I didn't expect it to work. Then when compiling:

```c
cc -std=gnu90 -Wall -Wextra -pedantic -Wno-trigraphs -Wno-incompatible-pointer-types -Wno-int-conversion -Wno-strict-prototypes  -include stdio.h -include stdlib.h -include time.h -Ugets -Ufgets -D'gets(x)'='fgets(x,232,stdin)' -O3 -trigraphs ldb.c -o ldb 
In file included from <built-in>:1:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:172:7: error: expected parameter declarator
char    *gets(char *);
         ^
<command line>:3:25: note: expanded from macro 'gets'
#define gets(x) fgets(x,232,stdin)
                        ^
In file included from <built-in>:1:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:172:7: error: expected ')'
<command line>:3:25: note: expanded from macro 'gets'
#define gets(x) fgets(x,232,stdin)
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:172:7: note: to match this '('
<command line>:3:22: note: expanded from macro 'gets'
#define gets(x) fgets(x,232,stdin)
                     ^
In file included from <built-in>:1:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:172:7: error: conflicting types for 'fgets'
char    *gets(char *);
         ^
<command line>:3:17: note: expanded from macro 'gets'
#define gets(x) fgets(x,232,stdin)
                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:149:7: note: previous declaration is here
char    *fgets(char * __restrict, int, FILE *);
         ^
ldb.c:1:98: warning: cast to 'time_t *' (aka 'long *') from smaller integer type 'int' [-Wint-to-pointer-cast]
int _,O,__??('}'??);main(){while(O?(gets((rand()%O++?':':_)+__))||puts(&__??(_??))&_:(srand(time((time_t *)(O+++_))),0)||O);}
                                                                                                 ^~~~~~~~~~~~~~~~~
1 warning and 3 errors generated.
make: *** [Makefile:137: ldb] Error 1
```

so it has to be in the source file it would appear. When I do work on this I'll also silence that warning that's now showing up. For another day though. I have news doctor wise - will say in other thread and then doing other things. Just had another moment to try this a bit more and by chance I was able to follow it - barely. It's quite frustrating as it's not like me to have so much trouble but I'm really unwell.

**Comment by lcn2** [comment]
# QUESTION

In general, should we change:

```make
CFLAGS= ${CSTD} ${CWARN} ${ARCH} ${CDEFINE} ${CINCLUDE} ${OPT}
```

to:

```make
CFLAGS= ${CSTD} ${CWARN} ${ARCH} ${CINCLUDE} ${CDEFINE}  ${OPT}
```

??

**Comment by xexyl** [comment]
> # QUESTION
> In general, should we change:
> 
> ```makefile
> CFLAGS= ${CSTD} ${CWARN} ${ARCH} ${CDEFINE} ${CINCLUDE} ${OPT}
> ```
> 
> to:
> 
> ```makefile
> CFLAGS= ${CSTD} ${CWARN} ${ARCH} ${CINCLUDE} ${CDEFINE}  ${OPT}
> ```
> 
> ??

At first I was thinking 'maybe' but then I remembered feature test macros so in general no. It might be that in some cases it can be useful but in general no. I know that in Snake I used feature test macros and I think I did in the Weasel words one too. I don't think I did in my Enigma machine.

So the answer is no except that maybe for some it might be useful ?

**Comment by lcn2** [comment]
> > # QUESTION
> > In general, should we change:
> > ```makefile
> > CFLAGS= ${CSTD} ${CWARN} ${ARCH} ${CDEFINE} ${CINCLUDE} ${OPT}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to:
> > ```makefile
> > CFLAGS= ${CSTD} ${CWARN} ${ARCH} ${CINCLUDE} ${CDEFINE}  ${OPT}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ??
> 
> At first I was thinking 'maybe' but then I remembered feature test macros so in general no. It might be that in some cases it can be useful but in general no. I know that in Snake I used feature test macros and I think I did in the Weasel words one too. I don't think I did in my Enigma machine.
> 
> So the answer is no except that maybe for some it might be useful ?

Perhaps if we reversed it by default and changed to only for those that need it the other way around?

In general case in C, we prefer to:

- comment
- system includes
- user includes
- defines
- variables
- forward declatations
- functions

So if `${CFLAGS}` were to follow that general order:

```
CFLAGS= ${CSTD} ${ARCH} ${OPT} ${CWARN} ${CINCLUDE} ${CDEFINE}
```

So perhaps those entries that need a different order could be the exception AND
that exception could be noted in the `REMARKS.md` file?

**Comment by xexyl** [comment]
An interesting thing about 1994/ldb with the `-D` option is this:

```c
cc  -trigraphs -D'srand(x)'='srand((x)),0'  ldb.c -include stdio.h -include time.h -include stdlib.h
In file included from <built-in>:3:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:164:7: error: expected identifier or '('
void     srand(unsigned) __swift_unavailable("Use arc4random instead.");
         ^
<command line>:1:29: note: expanded from macro 'srand'
#define srand(x) srand((x)),0
                            ^
In file included from <built-in>:3:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:164:7: error: expected ';' after top level declarator
<command line>:1:29: note: expanded from macro 'srand'
#define srand(x) srand((x)),0
                            ^
```

But why would it care that there isn't a `;` (which adding would cause a syntax error naturally). But here's an interesting bit that you probably can guess.

Change the code to use `frand`, say, and have that macro translate to `srand` and all is good. Meanwhile if we put the define as it was in the source code all is well. But why? I guess it's the phases of the compilation process but still it seems strange.

Now the real question is which is preferable of the options:

```c
#define gets(x) fgets((x),232,stdin)
#define srand(x) srand((x)),0
int _,O,__??('}'??);main(){while(O?(gets((rand()%O++?':':_)+__))||puts(&__??(_??))&_:(srand(time((time_t *)(O+++_))))||O);}
```

or remove the `srand` macro and keep the `,0` in the code?

Also as for the 232 originally that seems to be from `'}'` at least in part. I can't explain it without further looking at it as that value is definitely not 232 in decimal. I am either not thinking of something simple (very easy for me to do right now) or else it's the obfuscation that I've not looked at more (also quite possible). I figured it was that literal constant when I fixed it to use fgets but that was quite some time ago and since I fixed many other entries, many of which were much more twisted, I have no idea what if any conclusions I came to.

What do you think of all this? I have right now the one with both macros in the code so I could do a pull request I think if that's what you prefer. I still am trying to be careful and I don't want to do much until the regimen of medications is over later this week (though I might wait a few days after that at least) but I could at least do this - assuming I see a reply.

**Comment by xexyl** [comment]
> > Yes I think that if there are exceptions they can be done and then it is mentioned in the README.md - if that's what you mean? And possibly it can be referred to elsewhere in general? Maybe the FAQ will point out that in some cases the Makefile has the CFLAGS in different order?
> 
> Yes, good ideas.

If we have a todo list somewhere maybe it should be added? I know I have a todo list but I don't feel up to editing and committing it right now. But perhaps it shouldn't be done unless there are exceptions found.

**Comment by xexyl** [comment]
... another thing to consider with 1994/ldb is it's supposed to be 'best one-liner'. But with the macros it's no longer a one-liner. I don't know if this is a problem or not. Clearly it has to be noted in thanks file, bugs file and maybe the FAQ if it's done. But should it be done at all ? I don't know. I'm thinking perhaps not. It seems like it's even less authentic than after the compilation fix and getting rid of the annoying warning about `gets()`.

**Comment by lcn2** [comment]
> ... another thing to consider with 1994/ldb is it's supposed to be 'best one-liner'. But with the macros it's no longer a one-liner. I don't know if this is a problem or not. Clearly it has to be noted in thanks file, bugs file and maybe the FAQ if it's done. But should it be done at all ? I don't know. I'm thinking perhaps not. It seems like it's even less authentic than after the compilation fix and getting rid of the annoying warning about `gets()`.

It not being a 1-liner is a problem, yes.

**Comment by lcn2** [comment]
> ... another thing to consider with 1994/ldb is it's supposed to be 'best one-liner'. But with the macros it's no longer a one-liner. I don't know if this is a problem or not. Clearly it has to be noted in thanks file, bugs file and maybe the FAQ if it's done. But should it be done at all ? I don't know. I'm thinking perhaps not. It seems like it's even less authentic than after the compilation fix and getting rid of the annoying warning about `gets()`.

Turning a 1-liner into a non-1-liner is a problem.

**Comment by xexyl** [comment]
Re one-liners; agreed. It just didn't exactly register in my head that it WAS one until I was playing round with it and saw the output showing it. 

Which is one of the reasons I don't think I am yet ready to work on the repos. 

But I have to say I do feel bad about it because this is delaying the next contest 😩

I hope that by next week I can start doing things here and over there at the other repo (I wanted to say 'here and there' for the pun but it could be confusing to some so I put it here .. and there, obviously! instead). 

I don't know but I hope to. As of the last two days (today will be day three) I am trying to work on sorting through photos of the almost month now which will take a lot of time but the last couple days I have got at least two days done each day. That doesn't mean that I can't work on the contest: after all I won't be able to spend all my free time on the contest anyway but right n@ I am trying to take most of the days easy. 

The past few days or so I have managed to be up a bit more but that means more time away from the laptop. But at that point I would already be done working on the contest anyway. 

Anyway I know that you understand and I don't have to but I want to anyway: I am so sorry for the delays and I really hope that it's back to normal again soon! Obviously the most important thing and part of that is it would mean I am better but even so I am so sad and frustrated that I haven't been able to work with you on the contest 🥲

Hope you're sleeping well. I did sleep in some. To almost five. That means that I got probably 10.5 to 11 hours of sleep but I still am so exhausted. That often goes even when I am not unwell but even so it feels more extreme right now. 

#Anyway I'm very sorry for the delays! I know I don't have to apologise but I feel badly about it all so I wish to. 

This was typed with my phone and I will possibly try resting now but I don't think I will be able to rest so I probably will turn the laptop on soon though I don't know what I will even be able to do at this point.

**Comment by xexyl** [comment]
As far as this issue goes: yesterday I had the thought that it might be good to make it more general. In other words go through all the fixes, briefly, and see if others can somehow be more similar to the original. 

I have actually tried to do this all along but it seems like it wouldn't hurt to have another pass at them. 

Anyway that's not for now but it did cross my mind. 

Going to try lying back now. Provide futile but going to try even if briefly.

**Comment by xexyl** [comment]
As far as the 1990/tbr one. There is a problem with this suggested change. It might work in part but it has to also have extra code due to the fact that `gets()` does not retain the newline but `fgets()` does.

Here is the diff with trying to change it back to closer to what it was originally before I fixed the compilation and made it so the text is not interspersed with a warning:

```diff
+int e(int x),r(int t,int o);
+#define gets(x) fgets(x,512,stdin)
+#define exit(x) (exit(x),1)
 #define D ,close(
 
 char              *c,q              [512              ],m[              256
 ],*v[           99], **u,        *i[3];int         f[2],p;main       (){for
  (m[m        [60]=   m[62      ]=32   ]=m[*      m=124   [m]=       9]=6;
-  e(-8)     ,(c=fgets(q,512,stdin),(c==NULL &&(exit(0),1))||(c[strlen(c)-1]='\0'),1)||(exit(0),0);r(0,0)
+  e(-8)     ,gets      (1+(    c=q)     )||      (exit    (0),0);   r(0,0)
```

So you can see it's more complicated than this. It might make it even less like the original but I'm not sure of that. What do you think?

I still don't feel up to playing with it now but I did want to have a quick go at it. Unfortunately the newline causes a problem.

Doing other things again. Hope you have a great day! I'm happy I got at least a few things in earlier but that's all for the day.

**Comment by lcn2** [comment]
> So you can see it's more complicated than this. It might make it even less like the original but I'm not sure of that. What do you think?

Seems OK as the main wiggly/snaky section remains in form.

**Comment by xexyl** [comment]
> > So you can see it's more complicated than this. It might make it even less like the original but I'm not sure of that. What do you think?
> 
> Seems OK as the main wiggly/snaky section remains in form.

Right but it doesn't work. The `gets()` part might be easy enough to fix - but that's not certain yet. But the `exit()` might need both a `,0` and a `,1` used. I don't remember if I encountered that or not but it seems like it as why else would I have done it this way (using both) if it wasn't necessary?

If so the redefining of exit cannot work unless we give it a second arg.

As it stands the patch I show will not work. I can try playing with it more another time though. I'll reply to other things later on hopefully today.

Hope you're sleeping by now.

**Comment by xexyl** [comment]
Made some progress here ... will either do more and then commit or commit and look at it more later.

**Comment by xexyl** [comment]
https://github.com/ioccc-src/temp-test-ioccc/pull/944/commits/32d992f94537408b932682f38e3ba3405bff9467 fixes it! I think you'll be happy with the result. The extra `exit()` was not even needed as it seems that the check for NULL of `fgets()` is also not needed.

I will look at more entries another time. Off to do other things for the day. I will update you on my condition in the other repo next as it is not too encouraging. I do hope that I can start doing more and more though. We shall see!

**Comment by xexyl** [comment]
With commit https://github.com/ioccc-src/temp-test-ioccc/pull/955/commits/88eef478aaff2e895fa649c558460d2b3013a61e this issue is resolved except for one - 1990/theorem.

This one is proving a problem. I can try and work it out later but I must go now. The question is is it worth it though? What do you think? There were many bugs fixed and compilation errors as well (or at least one compilation error).

**Comment by lcn2** [comment]
> With commit https://github.com/ioccc-src/temp-test-ioccc/pull/955/commits/88eef478aaff2e895fa649c558460d2b3013a61e this issue is resolved except for one - 1990/theorem.
> 
> 
> 
> This one is proving a problem. I can try and work it out later but I must go now. The question is is it worth it though? What do you think? There were many bugs fixed and compilation errors as well (or at least one compilation error).
> 
> 
> 
> 

The `1990/theorem` is a tricky one.  If you come up with better idea, thats fine.  Such a change could be added later.

We will close this issue per your recommendation and our thanks.

**Comment by xexyl** [comment]
> > With commit [88eef47](https://github.com/ioccc-src/temp-test-ioccc/commit/88eef478aaff2e895fa649c558460d2b3013a61e) this issue is resolved except for one - 1990/theorem.
> > This one is proving a problem. I can try and work it out later but I must go now. The question is is it worth it though? What do you think? There were many bugs fixed and compilation errors as well (or at least one compilation error).
> 
> The `1990/theorem` is a tricky one. If you come up with better idea, thats fine. Such a change could be added later.
> 
It is yes. It's still on my mind. Maybe I can play with it tomorrow or the next day.

> We will close this issue per your recommendation and our thanks.

Happy to help!
